version: '3.8'

services:
  mammo:
    build: .
    ports:
      - "3000-3006:3000-3006"
      - "33510-33530:33510-33530"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: "/breast_cancer_detection"
    volumes:
      - ./:/breast_cancer_detection
    command: "bash -c 'python start_api_services.py || sleep infinity'"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
