version: '3.8'

services:
  mammo:
    build: .
    container_name: mammo
    ports:
      - "3000-3006:3000-3006"
      - "33510-33530:33510-33530"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/home/user
    user: user
    restart: unless-stopped